package models.logging;

/**
 * Created by Mike on 22-7-2015.
 */
public enum LogActionType {
    LOGIN, LOGOFF, ACCESSCALENDAR, ACCESSGOALS, BUTTONPRESS, ACCESSADDACTIVITYPAGE, ADDEDACTIVITY, ACCESSGALLERY, ACCESSADDPICTUREPAGE, ADDEDPICTURE
}
